### ISSUE TITLE
Criar campo para informar nível das perguntas (níveis 1 e 2)

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/impact-measurement#18]

**Comment by renatomurasaki** [comment]
@wilsonmoura para discussão: pelo fato de uma pergunta poder estar relacionada a mais de um tipo de pergunta, essa classificação de nivel 1 e 2 fica mais complexa. Exemplo:

A pergunta A do tipo de página Z pode ser nível 1
A pergunta A do tipo de página Y pode ser nível 2
