### ISSUE TITLE
Avaliar arquitetura do IM tendo em vista a volumetria dos acessos no iAHx Regional

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/impact-measurement#21]
iAHx Regional chegou a 1 milhão de usuários em out/20, com 1,5 milhão de visitas e 3,5 milhões de páginas visitadas

**Comment by wilsonmoura** [comment]
A sugestão é modificar o comportamento atual de acesso às perguntas para evitar a carga automática das perguntas e só mostrá-las quando o usuário clicar na aba.

**Comment by wilsonmoura** [comment]
Realizado em:
- Plugin WP: bireme/impact-measurement-wp-plugin#13
- iAHx: bireme/iahx-opac#229
