### ISSUE TITLE
A interface não está respeitando a ordem predefinida das perguntas

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/impact-measurement#25]

**Comment by renatomurasaki** [comment]
![image](https://user-images.githubusercontent.com/1226218/102396263-f3b31980-3fba-11eb-8ad6-ff3ded867835.png)

![image](https://user-images.githubusercontent.com/1226218/102396301-075e8000-3fbb-11eb-8ae2-104734434839.png)

A primeira pergunta deveria estar na 4a. posição.

**Comment by renatomurasaki** [comment]
@wilsonmoura no tipo de página Document(WP), a ordem definida foi respeitada.

**Comment by renatomurasaki** [comment]
@wilsonmoura no tipo de página Search (WP plugin) a ordem está sendo respeitada com 5 perguntas

**Comment by renatomurasaki** [comment]
@wilsonmoura reproduzi erro na ordem no tipo de página Document (WP Plug-in) com 6 perguntas

**Comment by renatomurasaki** [comment]
@wilsonmoura  reproduzi o erro na ordem no tipo de página Document (iAHx) com 6 perguntas

**Comment by renatomurasaki** [comment]
@wilsonmoura continua com problemas a ordem:

![image](https://user-images.githubusercontent.com/1226218/102623166-d8fab500-4120-11eb-8f22-95b2d132bc18.png)
![image](https://user-images.githubusercontent.com/1226218/102623247-f891dd80-4120-11eb-92f6-b26fd30b700c.png)

**Comment by renatomurasaki** [comment]
@wilsonmoura algo não está bem... Agora as páginas que estavam respeitando a ordem das perguntas não estão mais. Veja as imagens abaixo. Parece que está em ordem decrescente...

![image](https://user-images.githubusercontent.com/1226218/102780346-80bbf100-4374-11eb-9b47-d027b0396295.png)
![image](https://user-images.githubusercontent.com/1226218/102780425-a77a2780-4374-11eb-8431-70605f1c2ee4.png)

**Comment by renatomurasaki** [comment]
@wilsonmoura Veja outro exemplo com a home do WP. Tampouco está obedecendo a ordem,

![image](https://user-images.githubusercontent.com/1226218/102780626-08096480-4375-11eb-8ac8-1c021f03408a.png)
![image](https://user-images.githubusercontent.com/1226218/102780653-12c3f980-4375-11eb-94e9-508a91ad5568.png)

**Comment by wilsonmoura** [comment]
@renatomurasaki olhei aqui e parece que a ordem dessa vez está correta (veja os prints abaixo). Isso se aplica para todas as outras páginas mencionadas. Peço que teste novamente e, caso a ordem esteja errada, talvez seja necessário limpar o cache da respectiva página (Shift+F5).

### Home (WP):

![102780626-08096480-4375-11eb-8ac8-1c021f03408a](https://user-images.githubusercontent.com/3779520/103237899-d6217080-4927-11eb-9137-faee08d0540e.png)

![screenshot-teste bvsalud org-2020 12 28-16_13_18](https://user-images.githubusercontent.com/3779520/103237906-df124200-4927-11eb-997c-7e4ec286207a.png)

### Document (WP):

![102780346-80bbf100-4374-11eb-9b47-d027b0396295](https://user-images.githubusercontent.com/3779520/103238125-7ecfd000-4928-11eb-83da-912391705fb9.png)

![screenshot-teste bvsalud org-2020 12 28-16_17_15](https://user-images.githubusercontent.com/3779520/103238134-84c5b100-4928-11eb-94c1-53b5a4263575.png)

### Document (iAHx):

![102623166-d8fab500-4120-11eb-8f22-95b2d132bc18](https://user-images.githubusercontent.com/3779520/103238146-8e4f1900-4928-11eb-9eee-c94122e79f08.png)

![screenshot-pesquisa teste bvsalud org-2020 12 28-16_18_07](https://user-images.githubusercontent.com/3779520/103238162-98711780-4928-11eb-812e-91c637df4fc3.png)
