### ISSUE TITLE
Por que https://teste.bvsalud.org/como-pesquisar/ não mostra o formulário do IM?

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/impact-measurement#26]
O esperado era mostrar as perguntas selecionadas para o tipo de página Document (WP)

**Comment by wilsonmoura** [comment]
@renatomurasaki percebi um comportamento específico quando o post/página é criado usado o Page Builder. Provavelmente o tipo de página muda quando os conteúdos são criados/atualizados usando esse plugin (aba Page Builder no editor de texto). Para corrigir, tive que entrar no editor, escolher a aba Visual e atualizar a página. Vamos ter que investigar qual é o tipo de página que o WP assume nessas condições, visto que muitos conteúdos usam esse plugin para facilitar a publicação de conteúdos.

**Comment by renatomurasaki** [comment]
Ok, @wilsonmoura !
